### ISSUE TITLE
version '*' is not supported

### ISSUE THREAD

**Issue by AVVS** [delvedor/semver-store#4]
IMO, its nice to support that - just return the highest available version from all of the versions
What do you think?

**Comment by delvedor** [comment]
That could be a nice feature and it should not be hard to implement actually.
Do you want to send a pr? :)

**Comment by AVVS** [comment]
#5 should make this work, bench seems more or less the same with & without the change on 9.11.1

**Comment by delvedor** [comment]
Closed in #5
