### ISSUE TITLE
[Feature request] Support version fallback option

### ISSUE THREAD

**Issue by jk1z** [delvedor/semver-store#7]
It would be nice to have a fallback option in semver-store. If the version we are looking for is not in the store then we automatically fallback to a lower version then the one we are looking for.

What do you think?

**Comment by jk1z** [comment]
The algorithm will be something like - 
When we are getting a node by version number in prefix tree. 
If the node we are looking for is null, then get a max in the current node's leaves that is lower than the number we are looking for. 
If there is no number lower than the one we are looking for, fallback to the previous node and get the max number there. 
If there is no previous node, return null.

**Comment by delvedor** [comment]
Hello! This behavior is already supported :)
For example, If you add three nodes: `1.2.5`, `1.2.6`, `1.3.5`  and then use `1.2.x` you will get `1.2.6`, while it you use `1.x` you will get `1.3.5`.
It does not make sense doing the same for major versions, as a major version usually means “breaking change” or “fundamentally different”.

**Comment by jk1z** [comment]
@delvedor Ok, I see 😔. My current situation is that in the backend there are some routes in v3 and some routes are in v2 or v1. The reason I would want major version fallback is that for convenient reason. Currently, frontend will always request the routes in the latest major version, and our routing plugin will select the next available version.

for example:
The route only available in v1 however overall most of the routes are in v3. And since the client will request the routes in latest major version. Ideally when it does 3.x in the version header I would like to have that v1 route to response.

**Comment by jk1z** [comment]
But then I guess this might be a special case

**Comment by delvedor** [comment]
If your frontend is flexible enough to be able to work with different majors, I would recommend to use the `*` as version number, which will give you the highest version back.
